name: WorldRiptideCanceller
version: @version@
main: com.github.rnlin430.worldriptidecanceller.WorldRiptideCanceller
api-version: 1.15
description: WorldRiptideCanceller

commands:
  wrc:
    description: It's main commands of this plugin.
    aliases: [wr]
    usage:
      /<command>
      /wr
    permisson: worldriptidecanceller.command.wr
    permission-message: You don't have the permission "<permission>".


permissions:
  worldriptidecanceller.command.wrc:
    description: wrc command
    default: op
  worldriptidecanceller.ignoreriptidecancell:
    description: ignore riptide cancellation
    default: op


